dist: xenial
language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
script:
- pytest
deploy:
  provider: pypi
  user: harihar
  password:
    secure: USILOHuc21lQ+RNTpcbgwdzph6g494ZxAUiUipZvvg3U/nps14fxez+PkWCQDjNic+eFfsq+0NxxvpL4XcmUSg1TG0p6goMvF1iY0RUdnEjjqLC0xKhv8DmwtaLvyDDgm2CjUlIOfp8HIb4J1VdftHrAfD6kqFd8l2Urwym0wdPoaqzPJI1LVVH2pTGRo4aJ6Tu1PxYA5oWGkBUSVTKEwiKmAcnzcmfstEVfloadwGX3aQuSoHHsZkmBe321RrHoVr1aeZ3rEVzmFxLg6i82jbqf9VsKUdoOPpW/5B+L9QyBHLNrZoRpdB/IRVpC+cpwp27rSklzBhhThW/pHOFj7v5CPRZbE7mSIQ0Zxk8kV9ctOisYZGXnaiIY78NYccw/KXazkjgOeG0wmsiUUzrW8KtUAPO0R/a5v/0S+qrB00NeG3lcvB5N1lNCKrUB7RJ4EOuoYBz4ACb63q2IrCkjDYHIJZqQjerDHZP5yCq5gmPCOrjxRUi+Pc2PxdkJ8AIjMsuIIzDd2VhcmvnrG3SKpqtp8yfRekZLVA5545knzIUUAFpMMxRD+cMUUWVToarRwCajhKNt9GYxozUCgKVEhw8c1ALUquVP54or6TYsonEy918d0fPG9mBDWBl56BHJ1mU8buKH2A9ztBiL5eH5EElnceX1gZDbZYWVg+Urys8=
  on:
    tags: true
    branch: master
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
